config/routes.rb
Blog::Application.routes.draw do
    scope :controller => :page do
        get '/about', :to => :view_about, :as => 'blog_about'
    end

    scope :controller => :post do
        get '/category/(:tags)', :to => :view_category, :as => 'blog_category'
        get '/series/(:series)', :to => :view_series, :as => 'blog_series'
        get '/:title', :to => :view_single, :as => 'blog_post'
        get '/', :to => :view_single, :constraints => lambda { |request| request.query_string[/(?<=id=)\d+$/] }, :as => 'blog_post_id'
        get '/', :to => :view_all, :as => 'blog'
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :author, :length => { :maximum => 50 }
    validates :title, :length => { :maximum => 250 }, :allow_nil => true, :allow_blank => true, :uniqueness => { :case_sensitive => false }
    validates :link, :length => { :maximum => 250 }, :allow_nil => true, :allow_blank => true, :uniqueness => { :case_sensitive => false }, :exclusion => { :in => %w[category series] }

    has_many :tags
    has_many :categories, :through => :tags, :dependent => :destroy

    has_one :chapter, :dependent => :destroy
    has_one :series, :through => :chapter

    def self.hash_from_info(info = {})
        post = {}

        if info['series']
            post[:series] = Series.where("replace(lower(name), ' ', '-') = :series", { :series => info['series'].to_s.downcase.gsub(/ /, '-') }).first || Series.create!({ :name => info['series'].to_s })
        else
            post[:series] = nil
        end

        if info['tags']
            if info['tags'].kind_of? Array
                post[:categories] = info['tags'].map { |t| Category.where("replace(lower(name), ' ', '-') = :tag", { :tag => t.to_s.downcase.gsub(/ /, '-') }).first || Category.create!({ :name => t.to_s }) }
            else
                post[:categories] = [Category.where("replace(lower(name), ' ', '-') = :tag", { :tag => info['tags'].to_s.downcase.gsub(/ /, '-') }).first || Category.create!({ :name => info['tags'].to_s })]
            end
        else
            post[:categories] = []
        end

        post[:title] = info['title'] ? info['title'].to_s : nil
        post[:link] = info['title'] ? info['title'].to_s.linkify : nil
        post[:author] = info['author'] ? info['author'].to_s : nil
        post[:date] = info['date']
        post[:content] = info['content'].to_s

        post
    end

    def self.create_with_info(info = {})
        create(hash_from_info(info))
    rescue ActiveRecord::RecordInvalid, ActiveRecord::UnknownAttributeError
        nil
    end

    def self.create_with_info!(info = {})
        create!(hash_from_info(info))
    end

    def update_with_info(info = {})
        post = self.class.hash_from_info(info)
        update(post)
    rescue ActiveRecord::RecordInvalid, ActiveRecord::UnknownAttributeError
        false
    end

    def update_with_info!(info = {})
        post = self.class.hash_from_info(info)
        update!(post)
    end

    def content_html
        file = Blog::Application.assets.find_asset(content)
        file ? file.source.html_safe : nil
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    BATCH_MAX = 10

    def view_single
        if params[:title] != nil
            @post = Post.where(:link => params[:title].downcase.gsub(/ /, '-')).first
        else
            @post = Post.find_by(:id => params[:id])
        end

        redirect_to('/404.html') if @post == nil
    end

    def view_category
        @categories = Category.order(:name => :asc)

        if params[:tags] != nil
            if params[:last_post_id] != nil
                respond_to do |format|
                    posts = Post.order(:date => :desc).where('posts.date < :last_post_id', { :last_post_id => Time.at(params[:last_post_id][5..-1].to_f / 1000).to_datetime }).joins(:categories).where("replace(lower(categories.name), ' ', '-') IN (:tags)", { :tags => params[:tags].downcase.gsub(/ /, '-').split('+') }).uniq.limit(BATCH_MAX)

                    html = render_to_string(:partial => 'post/posts', :locals => { :posts => posts })
                    format.json { render :json => { :finished => (posts.count == 0 or posts.last == Post.order(:date => :asc).joins(:categories).where("replace(lower(categories.name), ' ', '-') IN (:tags)", { :tags => params[:tags].downcase.gsub(/ /, '-').split('+') }).uniq.first), :posts => html } }
                end
            else
                @posts = Post.order(:date => :desc).joins(:categories).where("replace(lower(categories.name), ' ', '-') IN (:tags)", { :tags => params[:tags].downcase.gsub(/ /, '-').split('+') }).uniq.limit(BATCH_MAX)
            end
        else
            @posts = []
        end
    end

    def view_series
        if params[:series] != nil
            series_name = params[:series].downcase.gsub(/ /, '-')
            @series = Series.where("replace(lower(series.name), ' ', '-') = :series", { :series => series_name }).first.name

            if params[:last_post_id] != nil
                respond_to do |format|
                    posts = Post.order(:date => :desc).where('posts.date < :last_post_id', { :last_post_id => Time.at_timestamp(params[:last_post_id][5..-1]).to_datetime }).joins(:series).where("replace(lower(series.name), ' ', '-') = :series", { :series => series_name }).uniq.limit(BATCH_MAX)

                    html = render_to_string(:partial => 'post/posts', :locals => { :posts => posts })
                    format.json { render :json => { :finished => (posts.count == 0 or posts.last == Post.order(:date => :asc).joins(:series).where("replace(lower(series.name), ' ', '-') = :series", { :series => series_name }).uniq.first), :posts => html } }
                end
            else
                @posts = Post.order(:date => :desc).joins(:series).where("replace(lower(series.name), ' ', '-') = :series", { :series => series_name }).uniq.limit(BATCH_MAX)
            end
        else
            @series = Series.order(:name => :asc)
            @posts = []
        end
    end

    def view_all
        if params[:last_post_id] != nil
            respond_to do |format|
                posts = Post.order(:date => :desc).where('date < :last_post_id', { :last_post_id => Time.at_timestamp(params[:last_post_id][5..-1]).to_datetime }).limit(BATCH_MAX)

                html = render_to_string(:partial => 'post/posts', :locals => { :posts => posts })
                format.json { render :json => { :finished => (posts.count == 0 or posts.last == Post.order(:date => :asc).first), :posts => html } }
            end
        else
            @posts = Post.order(:date => :desc).limit(BATCH_MAX)
        end
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/_article.html.erb
<article id="post-<%= post.date.try(:to_time).try(:timestamp) %>">
    <header>
        <!--
        <% if post.title %>
            <h1 class="title-link"><%= link_to_unless_current(post.title, blog_post_path(:title => post.link)) %></h1>
        <% end %>
        -->
        <div class="right-sided">
            <% if post.date %>
                <h6><%= post.date.strftime('%B %-d %Y') %></h6>
            <% end %>
            <% if post.author %>
                <h6>by <%= post.author %></h6>
            <% end %>
        </div>
        <div class="left-sided">
            <% if post.series %>
                <h6 class="title-link"><%= link_to post.series.name, blog_series_path(post.series.name.gsub(/ /, '-')) %></h6>
            <% end %>
        </div>
    </header>
    <% if post.title %>
        <h1 class="title-link"><%= link_to_unless_current(post.title, blog_post_path(:title => post.link)) %></h1>
    <% end %>
    
    <%= post.content_html %>
</article>

app/views/post/_posts.html.erb
<% posts.each do |post| %>
    <%= render 'post/article', :post => post %>
<% end %>

app/views/post/view_all.html.erb
<%= yield %>
<section id="posts">
    <%= render 'post/posts', :posts => @posts %>
</section>

app/views/post/view_category.html.erb
<%= yield %>

<section id="tags">
    <% @categories.each do |c| %>
        <div class="rounded-toggle">
            <%= check_box_tag c.name %>
            <%= label_tag c.name %>
        </div>
    <% end %>
</section>

<section id="posts">
    <%= render 'post/posts', :posts => @posts %>
</section>

app/views/post/view_series.html.erb
<%= yield %>

<% if @series.kind_of? ActiveRecord::Relation %>
    <section id="series">
        <% @series.each do |series| %>
            <h1 class="title-link"><%= link_to series.name, blog_series_path(series.name.gsub(/ /, '-')) %></h1>
        <% end %>
    </section>
<% else %>
    <section id="series">
        <h1><%= @series %></h1>
    </section>

    <section id="posts">
        <%= render 'post/posts', :posts => @posts %>
    </section>
<% end %>

app/views/post/view_single.html.erb
<%= yield %>
<section id="posts">
    <%= render 'post/article', :post => @post %>
</section>
<!-- <section id="comments"> comments </section> -->