config/routes.rb
Blog::Application.routes.draw do
    scope :controller => :page do
        get '/about', :to => :view_about, :as => 'blog_about'
    end

    scope :controller => :post do
        get '/category/(:tags)', :to => :view_category, :as => 'blog_category'
        get '/series/(:series)', :to => :view_series, :as => 'blog_series'
        get '/:title', :to => :view_single, :as => 'blog_post'
        get '/', :to => :view_single, :constraints => lambda { |request| request.query_string[/(?<=id=)\d+$/] }, :as => 'blog_post_id'
        get '/', :to => :view_all, :as => 'blog'
    end
end

app/views/layouts/_header.html.erb
<header>
    <nav>
        <ul>
            <% if !current_page?(blog_about_path) %>
                <li><%= link_to "About", blog_about_path %></li>
            <% end %>
            <% if !current_page?(blog_path) %>
                <li><%= link_to "Blog", blog_path %></li>
            <% end %>
            <% if Rails.application.routes.recognize_path(request.original_fullpath)[:controller] == 'post' and Rails.application.routes.recognize_path(request.original_fullpath)[:action] != 'view_category' %>
                <li><%= link_to "Category", blog_category_path %></li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><%= @post.try(:title).try(:+, ' | ScrimpyCat') || "ScrimpyCat's Blog" %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <%= yield %>
</body>
</html>